### ISSUE TITLE
PhotoGrabber crashing on launch (64 bit only)

### ISSUE THREAD

**Issue by Vidrep** [HaikuArchives/PhotoGrabber#18]
Did a fresh install of hrev52359 x86_64, then a pkgman update.
Installed PhotoGrabber hpkg from HaikuDepot.
Application crashes on launch every time.

**Comment by korli** [comment]
Should be fixed in b0bfef1f089110bb540fe556aa580338c28d3415.

**Comment by Vidrep** [comment]
Still not working. I have PhotoGrabber 2.3.3-4 installed on two different PC's. One is running the Beta, the other one running the nightly release. Both crash on launch.
I have attached the debug report for each PC.
[PhotoGrabber-736-debug-01-10-2018-14-46-42.report.txt](https://github.com/HaikuArchives/PhotoGrabber/files/2434480/PhotoGrabber-736-debug-01-10-2018-14-46-42.report.txt)
[PhotoGrabber-914-debug-01-10-2018-14-41-58.report.txt](https://github.com/HaikuArchives/PhotoGrabber/files/2434482/PhotoGrabber-914-debug-01-10-2018-14-41-58.report.txt)

**Comment by Vidrep** [comment]
I added additional comment and data to this closed issue 4 and 5 days ago respectively
 https://github.com/haikuports/haikuports/issues/3112

**Comment by Vidrep** [comment]
I found the problem. PhotoGrabber will crash on 64 bit if libusb is not installed. After installing it works on both PC's (Beta and nightly). Is this a recipe issue?

**Comment by Vidrep** [comment]
To reproduce:
- Install 64 bit Haiku (Beta or nightly)
- Install PhotoGrabber (from HaikuDepot)
- Launch PhotoGrabber (it should crash)
- Install Sanity from HaikuDepot (it should now work)
- Uninstall Sanity (it should now crash again)
- Uninstalling libusb or sane-backends will not make a difference.

**Comment by Vidrep** [comment]
Korli, I ran llvm static analyzer on all the makefiles, and only the ptc plug-in comes up with errors.
Can I zip up the generated html report and send it to you, so you can determine whether they are real bugs or just false positives?

**Comment by Vidrep** [comment]
Fresh install of hrev52533 x86_64. Install PhotoGrabber from HaikuDepot. Launch PhotoGrabber from terminal.

```Welcome to the Haiku shell.

/boot/system/apps/PhotoGrabber> PhotoGrabber
PREF - problem load default download path setting: 
PREF - problem load plugin name: 
PREF - problem load camera name: 
PREF - problem loading debug file setting: 
becam_scrollview BView::_InitData(): resizing mode or flags swapped
Kill Thread
/boot/system/apps/PhotoGrabber
```

**Comment by Vidrep** [comment]
Below is the syslog after the crash, and the generated debugger report.

```KERN: Running first login script /boot/system/boot/first-login/default_deskbar_items.sh ...
KERN: package_daemon [65271951:   716] CommitTransactionHandler::_ChangePackageActivation(): activating 2, deactivating 0 packages
KERN: unknown [65282926:   716] Volume::_ChangeActivation(): 2 new packages, 0 old packages
KERN: unknown [65291843:   716] KERN: package "photograbber-2.3.3-4-x86_64.hpkg" activated
KERN: unknown [65298893:   716] KERN: package "libexif-0.6.21-2-x86_64.hpkg" activated
KERN: slab memory manager: created area 0xffffffffb0001000 (15916)
KERN: package_daemon [65772152:   716] Volume::_PackagesEntryCreated("libexif-0.6.21-2-x86_64.hpkg")
KERN: package_daemon [65780342:   716] Volume::_PackagesEntryCreated("photograbber-2.3.3-4-x86_64.hpkg")
KERN: runtime_loader: Cannot open file /boot/system/apps/PhotoGrabber/plugins/error: No such file or directory
KERN: vm_soft_fault: va 0x0 not covered by area in address space
KERN: vm_page_fault: vm_soft_fault returned error 'Bad address' on fault at 0x0, ip 0x0, write 0, user 1, thread 0x4c3
KERN: debug_server: Thread 1219 entered the debugger: Segment violation
KERN: stack trace, current PC (nil)  :
KERN:   (0x7fb109c5d7e0)  0x172b218a104  _ZN6Camera15MessageReceivedEP8BMessage + 0x444
KERN:   (0x7fb109c5d8c0)  0x1ae80501308  _ZN7BLooper15DispatchMessageEP8BMessageP8BHandler + 0x1e
KERN:   (0x7fb109c5d8d0)  0x1ae805016ce  _ZN7BLooper11task_looperEv + 0x200
KERN:   (0x7fb109c5d930)  0x1ae804ffff3  _ZN7BLooper7_task0_EPv + 0x2d
KERN:   (0x7fb109c5d950)  0x766765a8c6  thread_entry + 0x12
```

**Comment by Vidrep** [comment]
```Debug information for team /boot/system/apps/PhotoGrabber/PhotoGrabber (1214):
CPU(s): 8x Intel Core™ i7-3770
Memory: 15.88 GiB total, 557.39 MiB used
Haiku revision: hrev52533 Nov 15 2018 20:02:30 (x86_64)

Active Threads:
	thread 1214: PhotoGrabber (main)
	thread 1218: w>PhotoGrabber 
	thread 1220: team 1214 debug task 
	thread 1219: cameralooper 
		state: Exception (Segment violation)

		Frame		IP			Function Name
		-----------------------------------------------
		00000000	00000000	? 
			Unable to retrieve disassembly for IP 0: address not contained in any valid image.
		0x7fb109c5d7f0	0x172b2185895	CamInterface::getDevType() + 0x15 
		0x7fb109c5d8d0	0x172b218a0ff	Camera::MessageReceived(BMessage*) + 0x43f 
		0x7fb109c5d8e0	0x1ae80501305	BLooper::DispatchMessage(BMessage*, BHandler*) + 0x1b 
		0x7fb109c5d940	0x1ae805016c8	BLooper::task_looper() + 0x1fa 
		0x7fb109c5d960	0x1ae804fffed	BLooper::_task0_(void*) + 0x27 
		0x7fb109c5d980	0x766765a8c4	thread_entry + 0x10 
		00000000	0x7fff632f4260	commpage_thread_exit + 0 

		Registers:
			  rip:	0x0000000000000000
			  rsp:	0x00007fb109c5d7c8
			  rbp:	0x00007fb109c5d7e0
			  rax:	0x0000020d361bdaa0
			  rbx:	0x0000020d3630db30
			  rcx:	0x0000020d3620a320
			  rdx:	0x0000020d3620a320
			  rsi:	0x0000020d3630db30
			  rdi:	0x00007fb109c5d7dc
			   r8:	0x7fffffffffffffff
			   r9:	0x0000000000000000
			  r10:	0x0000000000000044
			  r11:	0x0000000000003202
			  r12:	0x0000000000000001
			  r13:	0x0000000000000000
			  r14:	0x0000000000000000
			  r15:	0x00007fb109c5d8f8
			   cs:	0x002b
			   ds:	0x0000
			   es:	0x0000
			   fs:	0x0000
			   gs:	0x0000
			   ss:	0x0023
			  st0:	nan
			  st1:	nan
			  st2:	nan
			  st3:	0
			  st4:	nan
			  st5:	nan
			  st6:	5.18e+04
			  st7:	9.98e+07
			  mm0:	{0, 0, 0, 0}
			  mm1:	{0x100, 0, 0, 0}
			  mm2:	{0x4, 0, 0, 0}
			  mm3:	{0, 0, 0, 0}
			  mm4:	{0, 0, 0, 0}
			  mm5:	{0, 0xffeb, 0, 0}
			  mm6:	{0, 0, 0, 0xca3f}
			  mm7:	{0x97ec, 0xe7d4, 0x8606, 0xbe46}
			 xmm0:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm1:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm2:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm3:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm4:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm5:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm6:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm7:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm8:	{0, 0, 0, 0, 0, 0, 0, 0}
			 xmm9:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm10:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm11:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm12:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm13:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm14:	{0, 0, 0, 0, 0, 0, 0, 0}
			xmm15:	{0, 0, 0, 0, 0, 0, 0, 0}

Loaded Images:
	ID		Text Base	Text End	Data Base	Data End	Type	Name
	--------------------------------------------------------------------------------
	7216	0x3aee36000	0x3aee44000	0x3af044000	0x3af045000	add-on 	/boot/system/add-ons/Translators/BMPTranslator
	7214	0xcf0c47000	0xcf0e11000	0xcf1011000	0xcf1117000	lib    	/boot/system/lib/libIlmImf-2_2.so.23.0.0
	7190	0x3d22c78000	0x3d22c88000	0x3d22e88000	0x3d22e89000	add-on 	/boot/system/add-ons/Translators/TGATranslator
	7189	0x3ead544000	0x3ead57d000	0x3ead77d000	0x3ead77e000	lib    	/boot/system/lib/libjpeg.so.9.3.0
	7174	0x40f60fb000	0x40f6107000	0x40f6306000	0x40f6308000	lib    	/boot/system/lib/libicuio.so.57.1
	7195	0x5257a8f000	0x5257a9b000	0x5257c9b000	0x5257c9d000	add-on 	/boot/system/add-ons/Translators/PPMTranslator
	7206	0x59db7a3000	0x59db7af000	0x59db9af000	0x59db9b0000	add-on 	/boot/system/add-ons/Translators/HVIFTranslator
	7205	0x5a15d63000	0x5a15d71000	0x5a15f70000	0x5a15f71000	add-on 	/boot/system/add-ons/Translators/ICOTranslator
	7194	0x656c41a000	0x656c42c000	0x656c62b000	0x656c62d000	add-on 	/boot/system/add-ons/Translators/PSDTranslator
	7169	0x661becd000	0x661bee2000	0x661c0e1000	0x661c0e3000	lib    	/boot/system/lib/libtranslation.so
	7171	0x766761b000	0x7667777000	0x7667977000	0x76679ca000	lib    	/boot/system/lib/libroot.so
	7180	0x86462af000	0x8646384000	0x8646584000	0x8646585000	lib    	/boot/system/lib/libzstd.so.1.3.5
	7173	0x87edac2000	0x87edd3f000	0x87edf3e000	0x87edf53000	lib    	/boot/system/lib/libicui18n.so.57.1
	7217	0x9c28928000	0x9c28935000	0x9c28b35000	0x9c28b36000	add-on 	/boot/system/add-ons/Translators/STXTTranslator
	7170	0x9efd2b4000	0x9efd2c9000	0x9efd4c8000	0x9efd4c9000	lib    	/boot/system/lib/libgcc_s.so.1
	7192	0xa3e8d5b000	0xa3e8d6d000	0xa3e8f6c000	0xa3e8f6e000	add-on 	/boot/system/add-ons/Translators/RTFTranslator
	7191	0xa7c9703000	0xa7c9712000	0xa7c9912000	0xa7c9913000	add-on 	/boot/system/add-ons/Translators/SGITranslator
	7184	0xaac51c9000	0xaac51db000	0xaac53da000	0xaac53dc000	add-on 	/boot/system/add-ons/Translators/WonderBrushTranslator
	7211	0xb208f32000	0xb208f35000	0xb209134000	0xb209135000	lib    	/boot/system/lib/libIexMath-2_2.so.23.0.0
	7204	0xbe0abda000	0xbe0ac4c000	0xbe0ae4c000	0xbe0ae4e000	lib    	/boot/system/lib/libopenjp2.so.2.3.0
	7188	0xbff2896000	0xbff2906000	0xbff2b05000	0xbff2b09000	lib    	/boot/system/lib/libtiff.so.5.3.0
	7179	0xc1a9f0c000	0xc1a9f28000	0xc1aa127000	0xc1aa128000	lib    	/boot/system/lib/libz.so.1.2.11
	7203	0xdd6eb20000	0xdd6eb2f000	0xdd6ed2e000	0xdd6ed2f000	lib    	/boot/system/lib/libicns.so.1.2.0
	7187	0xe5d54f2000	0xe5d5500000	0xe5d5700000	0xe5d5701000	add-on 	/boot/system/add-ons/Translators/TIFFTranslator
	7212	0xffc38a9000	0xffc38af000	0xffc3aae000	0xffc3aaf000	lib    	/boot/system/lib/libIlmThread-2_2.so.23.0.0
	7210	0x10a04d0a000	0x10a04d1f000	0x10a04f1e000	0x10a04f21000	lib    	/boot/system/lib/libIex-2_2.so.23.0.0
	7207	0x117f8a79000	0x117f8a8f000	0x117f8c8e000	0x117f8c90000	add-on 	/boot/system/add-ons/Translators/GIFTranslator
	7202	0x11963e9d000	0x11963eaa000	0x119640aa000	0x119640ab000	add-on 	/boot/system/add-ons/Translators/ICNSTranslator
	7200	0x11c9610d000	0x11c96176000	0x11c96375000	0x11c96380000	lib    	/boot/system/lib/libjasper.so.4.0.0
	7199	0x12123a02000	0x12123a16000	0x12123c16000	0x12123c18000	add-on 	/boot/system/add-ons/Translators/JPEG2000Translator
	7167	0x122c8bf7000	0x122c8d5f000	0x122c8f5f000	0x122c8f73000	lib    	/boot/system/lib/libstdc++.so.6.0.24
	7213	0x138430e5000	0x138430f7000	0x138432f6000	0x138432f7000	lib    	/boot/system/lib/libImath-2_2.so.23.0.0
	7193	0x13c316d7000	0x13c316f4000	0x13c318f3000	0x13c318f6000	add-on 	/boot/system/add-ons/Translators/RAWTranslator
	7208	0x1565eb2e000	0x1565eb3b000	0x1565ed3b000	0x1565ed3c000	add-on 	/boot/system/add-ons/Translators/EXRTranslator
	7175	0x1598a5de000	0x1598a633000	0x1598a833000	0x1598a836000	lib    	/boot/system/lib/libicule.so.57.1
	7166	0x172b2172000	0x172b2197000	0x172b2396000	0x172b2399000	app    	/boot/system/apps/PhotoGrabber/PhotoGrabber
	7209	0x18d5e4b0000	0x18d5e4f2000	0x18d5e6f1000	0x18d5e6f2000	lib    	/boot/system/lib/libHalf.so.23.0.0
	7185	0x18e5d9be000	0x18e5d9cc000	0x18e5dbcc000	0x18e5dbcd000	add-on 	/boot/system/add-ons/Translators/WebPTranslator
	7177	0x1934484f000	0x1934487e000	0x19344a7e000	0x19344ab2000	lib    	/boot/system/lib/libicutu.so.57.1
	7197	0x1a85363d000	0x1a85366e000	0x1a85386e000	0x1a85386f000	lib    	/boot/system/lib/libpng16.so.16.35.0
	7181	0x1a94f50c000	0x1a94f609000	0x1a94f809000	0x1a94f80c000	lib    	/boot/system/lib/libtextencoding.so
	7168	0x1ae803b5000	0x1ae806b9000	0x1ae808b9000	0x1ae808e7000	lib    	/boot/system/lib/libbe.so
	7165	0x1b3fe5f5000	0x1b3fe615000	0x1b3fe814000	0x1b3fe817000	lib    	/boot/system/runtime_loader
	7215	0x1f37766c000	0x1f37768d000	0x1f37788c000	0x1f37788e000	lib    	/boot/system/lib/libIlmImfUtil-2_2.so.23.0.0
	7201	0x1f4d7b4b000	0x1f4d7b62000	0x1f4d7d62000	0x1f4d7d64000	add-on 	/boot/system/add-ons/Translators/JPEGTranslator
	7198	0x1f9d8a41000	0x1f9d8a4d000	0x1f9d8c4d000	0x1f9d8c4e000	add-on 	/boot/system/add-ons/Translators/PCXTranslator
	7196	0x205cebce000	0x205cebdd000	0x205ceddd000	0x205cedde000	add-on 	/boot/system/add-ons/Translators/PNGTranslator
	7186	0x205df063000	0x205df0cc000	0x205df2cc000	0x205df2cf000	lib    	/boot/system/lib/libwebp.so.7.0.2
	7178	0x208c3628000	0x208c37c0000	0x208c39bf000	0x208c39d4000	lib    	/boot/system/lib/libicuuc.so.57.1
	7176	0x2453fac9000	0x2453fad4000	0x2453fcd4000	0x2453fcd5000	lib    	/boot/system/lib/libiculx.so.57.1
	7172	0x24864673000	0x24865ef1000	0x248660f0000	0x248660f1000	lib    	/boot/system/lib/libicudata.so.57.1
	7164	0x7fff632f4000	0x7fff632fc000	0x00000000	0x00000000	system 	commpage

Areas:
	ID		Base		End			Size (KiB)	Protection	Locking			Name
	--------------------------------------------------------------------------------
	19911	0x0a707000	0x0a71f000	        96	rw-        	full          	rld heap
	19910	0x0d380000	0x0d398000	        96	rw-        	full          	rld heap
	19921	0x60000000	0x60001000	         4	rw-S       	full          	server_memory
	19923	0x68000000	0x68020000	       128	rw-S       	full          	server_memory
	19909	0xfe934000	0xfe944000	        64	rw-        	full          	rld heap
	19994	0x3aee36000	0x3aee44000	        56	r-x        	full          	BMPTranslator_seg0ro
	19995	0x3af044000	0x3af045000	         4	rw-        	full          	BMPTranslator_seg1rw
	19908	0x458d54000	0x458d64000	        64	rw-        	full          	rld heap
	19907	0x912a25000	0x912a2d000	        32	rw-        	full          	rld heap
	19989	0xcf0c47000	0xcf0e11000	      1832	r-x        	full          	libIlmImf-2_2.so.23.0.0_seg0ro
	19990	0xcf1011000	0xcf1116000	      1044	rw-        	full          	libIlmImf-2_2.so.23.0.0_seg1rw
	19991	0xcf1116000	0xcf1117000	         4	rw-        	full          	libIlmImf-2_2.so.23.0.0_seg2rw
	19871	0xe965c2000	0xe965c3000	         4	rw-S       	full          	_rld_debug_
	19939	0x3d22c78000	0x3d22c88000	        64	r-x        	full          	TGATranslator_seg0ro
	19940	0x3d22e88000	0x3d22e89000	         4	rw-        	full          	TGATranslator_seg1rw
	19937	0x3ead544000	0x3ead57d000	       228	r-x        	full          	libjpeg.so.9.3.0_seg0ro
	19938	0x3ead77d000	0x3ead77e000	         4	rw-        	full          	libjpeg.so.9.3.0_seg1rw
	19890	0x40f60fb000	0x40f6107000	        48	r-x        	full          	libicuio.so.57.1_seg0ro
	19891	0x40f6306000	0x40f6308000	         8	rw-        	full          	libicuio.so.57.1_seg1rw
	19950	0x5257a8f000	0x5257a9b000	        48	r-x        	full          	PPMTranslator_seg0ro
	19951	0x5257c9b000	0x5257c9d000	         8	rw-        	full          	PPMTranslator_seg1rw
	19973	0x59db7a3000	0x59db7af000	        48	r-x        	full          	HVIFTranslator_seg0ro
	19974	0x59db9af000	0x59db9b0000	         4	rw-        	full          	HVIFTranslator_seg1rw
	19971	0x5a15d63000	0x5a15d71000	        56	r-x        	full          	ICOTranslator_seg0ro
	19972	0x5a15f70000	0x5a15f71000	         4	rw-        	full          	ICOTranslator_seg1rw
	19947	0x656c41a000	0x656c42c000	        72	r-x        	full          	PSDTranslator_seg0ro
	19948	0x656c62b000	0x656c62c000	         4	rw-        	full          	PSDTranslator_seg1rw
	19949	0x656c62c000	0x656c62d000	         4	rw-        	full          	PSDTranslator_seg2rw
	19879	0x661becd000	0x661bee2000	        84	r-x        	full          	libtranslation.so_seg0ro
	19880	0x661c0e1000	0x661c0e3000	         8	rw-        	full          	libtranslation.so_seg1rw
	19870	0x6fe85f6000	0x6fe8606000	        64	rw-        	full          	rld heap
	19883	0x766761b000	0x7667777000	      1392	r-x        	full          	libroot.so_seg0ro
	19884	0x7667977000	0x7667985000	        56	rw-        	full          	libroot.so_seg1rw
	19885	0x7667985000	0x76679ca000	       276	rw-        	full          	libroot.so_seg2rw
	19903	0x86462af000	0x8646384000	       852	r-x        	full          	libzstd.so.1.3.5_seg0ro
	19904	0x8646584000	0x8646585000	         4	rw-        	full          	libzstd.so.1.3.5_seg1rw
	19888	0x87edac2000	0x87edd3f000	      2548	r-x        	full          	libicui18n.so.57.1_seg0ro
	19889	0x87edf3e000	0x87edf53000	        84	rw-        	full          	libicui18n.so.57.1_seg1rw
	19996	0x9c28928000	0x9c28935000	        52	r-x        	full          	STXTTranslator_seg0ro
	19997	0x9c28b35000	0x9c28b36000	         4	rw-        	full          	STXTTranslator_seg1rw
	19881	0x9efd2b4000	0x9efd2c9000	        84	r-x        	full          	libgcc_s.so.1_seg0ro
	19882	0x9efd4c8000	0x9efd4c9000	         4	rw-        	full          	libgcc_s.so.1_seg1rw
	19943	0xa3e8d5b000	0xa3e8d6d000	        72	r-x        	full          	RTFTranslator_seg0ro
	19944	0xa3e8f6c000	0xa3e8f6e000	         8	rw-        	full          	RTFTranslator_seg1rw
	19941	0xa7c9703000	0xa7c9712000	        60	r-x        	full          	SGITranslator_seg0ro
	19942	0xa7c9912000	0xa7c9913000	         4	rw-        	full          	SGITranslator_seg1rw
	19926	0xaac51c9000	0xaac51db000	        72	r-x        	full          	WonderBrushTranslator_seg0ro
	19927	0xaac53da000	0xaac53dc000	         8	rw-        	full          	WonderBrushTranslator_seg1rw
	19983	0xb208f32000	0xb208f35000	        12	r-x        	full          	libIexMath-2_2.so.23.0.0_seg0ro
	19984	0xb209134000	0xb209135000	         4	rw-        	full          	libIexMath-2_2.so.23.0.0_seg1rw
	19969	0xbe0abda000	0xbe0ac4c000	       456	r-x        	full          	libopenjp2.so.2.3.0_seg0ro
	19970	0xbe0ae4c000	0xbe0ae4e000	         8	rw-        	full          	libopenjp2.so.2.3.0_seg1rw
	19935	0xbff2896000	0xbff2906000	       448	r-x        	full          	libtiff.so.5.3.0_seg0ro
	19936	0xbff2b05000	0xbff2b09000	        16	rw-        	full          	libtiff.so.5.3.0_seg1rw
	19901	0xc1a9f0c000	0xc1a9f28000	       112	r-x        	full          	libz.so.1.2.11_seg0ro
	19902	0xc1aa127000	0xc1aa128000	         4	rw-        	full          	libz.so.1.2.11_seg1rw
	19967	0xdd6eb20000	0xdd6eb2f000	        60	r-x        	full          	libicns.so.1.2.0_seg0ro
	19968	0xdd6ed2e000	0xdd6ed2f000	         4	rw-        	full          	libicns.so.1.2.0_seg1rw
	19933	0xe5d54f2000	0xe5d5500000	        56	r-x        	full          	TIFFTranslator_seg0ro
	19934	0xe5d5700000	0xe5d5701000	         4	rw-        	full          	TIFFTranslator_seg1rw
	19985	0xffc38a9000	0xffc38af000	        24	r-x        	full          	libIlmThread-2_2.so.23.0.0_seg0
	19986	0xffc3aae000	0xffc3aaf000	         4	rw-        	full          	libIlmThread-2_2.so.23.0.0_seg1
	19981	0x10a04d0a000	0x10a04d1f000	        84	r-x        	full          	libIex-2_2.so.23.0.0_seg0ro
	19982	0x10a04f1e000	0x10a04f21000	        12	rw-        	full          	libIex-2_2.so.23.0.0_seg1rw
	19975	0x117f8a79000	0x117f8a8f000	        88	r-x        	full          	GIFTranslator_seg0ro
	19976	0x117f8c8e000	0x117f8c90000	         8	rw-        	full          	GIFTranslator_seg1rw
	19965	0x11963e9d000	0x11963eaa000	        52	r-x        	full          	ICNSTranslator_seg0ro
	19966	0x119640aa000	0x119640ab000	         4	rw-        	full          	ICNSTranslator_seg1rw
	19960	0x11c9610d000	0x11c96176000	       420	r-x        	full          	libjasper.so.4.0.0_seg0ro
	19961	0x11c96375000	0x11c9637a000	        20	rw-        	full          	libjasper.so.4.0.0_seg1rw
	19962	0x11c9637a000	0x11c96380000	        24	rw-        	full          	libjasper.so.4.0.0_seg2rw
	19958	0x12123a02000	0x12123a16000	        80	r-x        	full          	JPEG2000Translator_seg0ro
	19959	0x12123c16000	0x12123c18000	         8	rw-        	full          	JPEG2000Translator_seg1rw
	19874	0x122c8bf7000	0x122c8d5f000	      1440	r-x        	full          	libstdc++.so.6.0.24_seg0ro
	19875	0x122c8f5f000	0x122c8f6b000	        48	rw-        	full          	libstdc++.so.6.0.24_seg1rw
	19876	0x122c8f6b000	0x122c8f73000	        32	rw-        	full          	libstdc++.so.6.0.24_seg2rw
	19987	0x138430e5000	0x138430f7000	        72	r-x        	full          	libImath-2_2.so.23.0.0_seg0ro
	19988	0x138432f6000	0x138432f7000	         4	rw-        	full          	libImath-2_2.so.23.0.0_seg1rw
	19945	0x13c316d7000	0x13c316f4000	       116	r-x        	full          	RAWTranslator_seg0ro
	19946	0x13c318f3000	0x13c318f6000	        12	rw-        	full          	RAWTranslator_seg1rw
	19977	0x1565eb2e000	0x1565eb3b000	        52	r-x        	full          	EXRTranslator_seg0ro
	19978	0x1565ed3b000	0x1565ed3c000	         4	rw-        	full          	EXRTranslator_seg1rw
	19892	0x1598a5de000	0x1598a633000	       340	r-x        	full          	libicule.so.57.1_seg0ro
	19893	0x1598a833000	0x1598a836000	        12	rw-        	full          	libicule.so.57.1_seg1rw
	19872	0x172b2172000	0x172b2197000	       148	r-x        	full          	PhotoGrabber_seg0ro
	19873	0x172b2396000	0x172b2399000	        12	rw-        	full          	PhotoGrabber_seg1rw
	19979	0x18d5e4b0000	0x18d5e4f2000	       264	r-x        	full          	libHalf.so.23.0.0_seg0ro
	19980	0x18d5e6f1000	0x18d5e6f2000	         4	rw-        	full          	libHalf.so.23.0.0_seg1rw
	19928	0x18e5d9be000	0x18e5d9cc000	        56	r-x        	full          	WebPTranslator_seg0ro
	19929	0x18e5dbcc000	0x18e5dbcd000	         4	rw-        	full          	WebPTranslator_seg1rw
	19896	0x1934484f000	0x1934487e000	       188	r-x        	full          	libicutu.so.57.1_seg0ro
	19897	0x19344a7e000	0x19344a80000	         8	rw-        	full          	libicutu.so.57.1_seg1rw
	19898	0x19344a80000	0x19344ab2000	       200	rw-        	full          	libicutu.so.57.1_seg2rw
	19954	0x1a85363d000	0x1a85366e000	       196	r-x        	full          	libpng16.so.16.35.0_seg0ro
	19955	0x1a85386e000	0x1a85386f000	         4	rw-        	full          	libpng16.so.16.35.0_seg1rw
	19905	0x1a94f50c000	0x1a94f609000	      1012	r-x        	full          	libtextencoding.so_seg0ro
	19906	0x1a94f809000	0x1a94f80c000	        12	rw-        	full          	libtextencoding.so_seg1rw
	19877	0x1ae803b5000	0x1ae806b9000	      3088	r-x        	full          	libbe.so_seg0ro
	19878	0x1ae808b9000	0x1ae808e7000	       184	rw-        	full          	libbe.so_seg1rw
	19868	0x1b3fe5f5000	0x1b3fe615000	       128	r-x        	full          	runtime_loader_seg0ro
	19869	0x1b3fe814000	0x1b3fe817000	        12	rw-        	full          	runtime_loader_seg1rw
	19992	0x1f37766c000	0x1f37768d000	       132	r-x        	full          	libIlmImfUtil-2_2.so.23.0.0_seg
	19993	0x1f37788c000	0x1f37788e000	         8	rw-        	full          	libIlmImfUtil-2_2.so.23.0.0_seg
	19963	0x1f4d7b4b000	0x1f4d7b62000	        92	r-x        	full          	JPEGTranslator_seg0ro
	19964	0x1f4d7d62000	0x1f4d7d64000	         8	rw-        	full          	JPEGTranslator_seg1rw
	19956	0x1f9d8a41000	0x1f9d8a4d000	        48	r-x        	full          	PCXTranslator_seg0ro
	19957	0x1f9d8c4d000	0x1f9d8c4e000	         4	rw-        	full          	PCXTranslator_seg1rw
	19952	0x205cebce000	0x205cebdd000	        60	r-x        	full          	PNGTranslator_seg0ro
	19953	0x205ceddd000	0x205cedde000	         4	rw-        	full          	PNGTranslator_seg1rw
	19930	0x205df063000	0x205df0cc000	       420	r-x        	full          	libwebp.so.7.0.2_seg0ro
	19931	0x205df2cc000	0x205df2cd000	         4	rw-        	full          	libwebp.so.7.0.2_seg1rw
	19932	0x205df2cd000	0x205df2cf000	         8	rw-        	full          	libwebp.so.7.0.2_seg2rw
	19899	0x208c3628000	0x208c37c0000	      1632	r-x        	full          	libicuuc.so.57.1_seg0ro
	19900	0x208c39bf000	0x208c39d4000	        84	rw-        	full          	libicuuc.so.57.1_seg1rw
	19912	0x20d36183000	0x20d364a3000	      3200	rw-        	full          	heap
	19894	0x2453fac9000	0x2453fad4000	        44	r-x        	full          	libiculx.so.57.1_seg0ro
	19895	0x2453fcd4000	0x2453fcd5000	         4	rw-        	full          	libiculx.so.57.1_seg1rw
	19886	0x24864673000	0x24865ef1000	     25080	r-x        	full          	libicudata.so.57.1_seg0ro
	19887	0x248660f0000	0x248660f1000	         4	rw-        	full          	libicudata.so.57.1_seg1rw
	19999	0x7fa0719ef000	0x7fa071a34000	       276	rw-s       	full          	w>PhotoGrabber_1218_stack
	20001	0x7fb109c1a000	0x7fb109c5f000	       276	rw-s       	full          	cameralooper_1219_stack
	19866	0x7fb300efd000	0x7fb301f03000	     16408	rw-s       	full          	PhotoGrabber_1214_stack
	19865	0x7ff2978e9000	0x7ff2978ed000	        16	rw-        	full          	user area
	19867	0x7fff632f4000	0x7fff632fc000	        32	r-xSk      	full          	commpage

Protection Flags: r - read, w - write, x - execute, s - stack, o - overcommit, c - cloneable, S - shared, k - kernel

Semaphores:
	ID		Count	Last Holder	Name
	------------------------------------------------------------
	6566	    0	          0	some BBlockCache lock
	6567	    0	          0	Catalog
	6568	    0	          0	some BLocker
	6569	    0	          0	some BLocker
	6570	    0	          0	token space
	6571	    0	          0	BLooperList lock
	6572	    0	          0	AppServerLink_sLock
	6573	    0	          0	LocaleRosterData
	6574	    0	          0	some BLocker
	6575	    0	          0	Catalog
	6576	    0	          0	BMessageQueue Lock
	6577	    0	          0	AppLooperPort
	6589	    0	          0	screen list
	6590	    0	          0	clipboard
	6591	    0	          0	width buffer
	6592	    0	          0	BMessageQueue Lock
	6593	    0	          0	PhotoGrabber
	6599	    0	          0	translator list
	6600	    0	          0	Catalog
	6601	    0	          0	TranslatorSettings Lock
	6602	    0	          0	Catalog
	6603	    0	          0	TranslatorSettings Lock
	6604	    0	          0	Catalog
	6605	    0	          0	TranslatorSettings Lock
	6606	    0	          0	Catalog
	6607	    0	          0	TranslatorSettings Lock
	6608	    0	          0	Catalog
	6609	    0	          0	TranslatorSettings Lock
	6610	    0	          0	Catalog
	6611	    0	          0	Catalog
	6612	    0	          0	TranslatorSettings Lock
	6613	    0	          0	Catalog
	6614	    0	          0	TranslatorSettings Lock
	6615	    0	          0	PPM settings lock
	6616	    0	          0	Catalog
	6617	    0	          0	TranslatorSettings Lock
	6618	    0	          0	Catalog
	6619	    0	          0	TranslatorSettings Lock
	6620	    0	          0	Catalog
	6621	    0	          0	TranslatorSettings Lock
	6622	    0	          0	Catalog
	6623	    0	          0	TranslatorSettings Lock
	6624	    0	          0	Catalog
	6625	    0	          0	TranslatorSettings Lock
	6626	    0	          0	Catalog
	6627	    0	          0	TranslatorSettings Lock
	6628	    0	          0	Catalog
	6629	    0	          0	TranslatorSettings Lock
	6630	    0	          0	Catalog
	6631	    0	          0	TranslatorSettings Lock
	6632	    0	          0	Catalog
	6633	    0	          0	TranslatorSettings Lock
	6634	    0	          0	Catalog
	6635	    0	          0	TranslatorSettings Lock
	6636	    0	          0	Catalog
	6637	    0	          0	TranslatorSettings Lock
	6641	    0	          0	BMessageQueue Lock
	6642	    0	          0	cameralooper
	6678	    0	          0	tool tip manager
```

**Comment by Vidrep** [comment]
Tested with hrev53182 x86_64. Not crashing on launch, nor is there any more need to install Sanity to make it work. Closing as fixed.
